18F/dsnap-registration

src/app.js, src/components/app-container.js, src/components/no-match.js, src/routes.js
=> Adds basic routes + modifies app container

src/app.js, src/components/dropdown/dropdown.test.js, src/components/dropdown/index.js, src/components/input/index.js, src/components/input/input-error.js, src/components/input/input.css, src/components/input/input.test.js, src/components/radio-checkbox/index.js, src/components/radio-checkbox/radio-checkbox.test.js, src/index.js, src/routes.js
* Adds basic dropdown component
* Adds basic checkbox/radio inputs
* Adds basic text / number input and error handling
=> Adds tests and components for some form elements

package.json, src/app.js, src/components/app-container.js, src/components/collapsible/collapsible-content.js, src/components/collapsible/index.js, src/components/dropdown/index.js, src/components/header/index.js, src/components/input/index.js, src/components/radio-checkbox/index.js, src/index.js, yarn.lock
* removes ref to service worker
* normalizes parens in stateless components
* use class binding and state property syntax style, removes unused
constructors
=> *minor cleanup of code

.circleci/config.yml, manifest.yml, package.json
Attempting to get circle and cloud foundry working
=> Adds cloudgov and circle files

src/app.css, src/components/button/index.js, src/components/collapsible/collapsible-content.js, src/components/collapsible/collapsible.test.js, src/components/collapsible/index.js, src/components/icons/lock.js, src/components/scroll-to-top.js, src/components/ui/index.js, src/components/wizard/debug.js, src/i18n.js, src/locales/en/translation.json, src/locales/index.js, src/locales/utils.js, src/pages/form/basic-info.js, src/pages/form/basic-info/index.js, src/pages/form/basic-info/intro.js, src/routes.js
* Adds `ui` folder for generic ui components
* Adds translation strings for intro page
* Adds skeleton intro
**screenshot**
=> First pass at basic info intro page

src/components/formik-field/index.js, src/components/radio-checkbox/index.js, src/components/radio-checkbox/radio-checkbox.test.js, src/components/wizard/index.js, src/locales/en/translation.json, src/models/basic-info.js, src/models/identity.js, src/models/personal-info.js, src/pages/form/steps/applicant-name.js, src/pages/form/steps/index.js, src/pages/form/steps/residence-address.js, src/route-config.js
* Fix bug where checkbox wasnt working with formik by retriggering a
click on the input element
* moves some data into identity from basic info
=> Adds primary address page

src/models/address.js, src/pages/form/steps/index.js, src/pages/form/steps/mailing-address.js, src/route-config.js
Mailing address page is navigable via url bar
=> Adds mailing address page

src/components/formik-field/index.js, src/components/radio-checkbox/index.js, src/locales/en/translation.json, src/pages/form/steps/residence-address.js
* First pass, likely still needs tweaks
* Need to separate translation and data
=> Style checkboxes to better match designs

src/fsm-config.js, src/locales/en/translation.json, src/models/household.js, src/models/index.js, src/models/person.js, src/pages/form/sections/household.js, src/pages/form/sections/index.js, src/pages/form/steps/basic-info/applicant-name.js, src/pages/form/steps/household/get-prepared.js, src/pages/form/steps/household/how-many.js, src/pages/form/steps/household/index.js, src/pages/form/steps/household/member-details.js, src/pages/form/steps/household/member-names.js, src/pages/form/steps/index.js, src/route-config.js
* Adds basic states in fsm
* Adds section component
* Adds step components
* Updates `route-config`
=> Basic set up for household section

package.json, src/app.scss, src/components/combo-field/combo-field.scss, src/components/combo-field/index.js, src/components/formik-field/index.js, src/components/fsm.js, src/components/input/index.js, src/components/wizard/index.js, src/components/yes-no-field/index.js, src/fsm-config.js, src/index.js, src/locales/en/translation.json, src/models/impact.js, src/pages/form/steps/impact/index.js, src/pages/form/steps/index.js, src/route-config.js, yarn.lock
Fields and content are represented, validations are not
=> Adds adverse-effects step to form

.circleci/config.yml, package.json, src/components/combo-field/index.js, src/components/dropdown/index.js, src/components/formik-field/index.js, src/components/fsm.js, src/components/input/index.js, src/components/loading.js, src/components/radio-checkbox/index.js, src/components/with-form-field/index.js, src/components/wizard/index.js, src/fsm-config.js, src/locales/en/translation.json, src/models/basic-info.js, src/models/config.js, src/models/disaster.js, src/pages/form/steps/household/how-many.js, src/pages/form/steps/impact/index.js, src/pages/form/steps/resources/assets.js, src/pages/form/steps/resources/income.js, src/pages/pre-registration/index.js, src/services/disaster.js, src/validators/basic-info/name.js, yarn.lock
* Disasters are fetched on the pre-registration step
* Selected disaster and affected county are stored in the state machine's context
* Adds very basic loading component for async calls
* Adds basic error message when service can't be reached
=> Adds code to fetch and display disasters

src/fsm-config.js, src/pages/pre-registration/index.js, src/pages/prepare/index.js, src/pages/welcome/index.js, src/route-config.js, src/routes.js
* Routing now follows correct flow based on sketch / ui design
* Use strings in local storage option
=> Nest preparation page under form

src/components/formik-field/index.js, src/components/masked-input.js, src/components/review/basic-info.js, src/components/review/household.js, src/components/wizard/index.js, src/models/disaster.js, src/pages/form/steps/basic-info/residence-address.js, src/pages/form/steps/household/member-details.js, src/pages/form/steps/identity/index.js, src/pages/pre-registration/index.js, src/utils.js
Handles basic input masking based on developer-supplied `pattern` and `delimiter` values. Does not accommodate nested / recursive masks.
=> Adds basic MaskedInput component

src/locales/en/translation.json, src/pages/form/steps/basic-info/offramp.js
* Copy still makes references to the ability to stop working on the form
and apply another way, will be addressed in a followup ticket
=> Remove green box and submit info

src/components/review-table.js, src/components/review/income.js, src/models/applicable.js, src/models/impact.js, src/models/income-sources.js
* Adds shared method to interact with applicable data type
=> update expense and income totals on review page

src/components/review/household.js, src/components/wizard/index.js, src/pages/form/steps/review/index.js
* Fixes bug where parent formik instance didn't know about new household
members being added in the review section
=> Pass handler to write parent form values as props

src/components/review/income.js, src/locales/en/translation.json, src/models/job.js, src/pages/form/steps/resources/jobs.js, src/test-data.js
* We need to be more specific about the type of government work we want
to capture form customers
=> Changes isStateAgency to isDsnapAgency

src/models/household.js, src/test-data.js
* Don't push extra blank members into household.members without checking
to see if the household count reflects the current number of members in
the list
=> Fix bug in member loop

src/pages/pre-registration/index.js, src/test-data.js
=> Adds disaster description to pre-registration disaster selector

src/fsm-config.js, src/pages/form/steps/resources/jobs.js
* Should make validation of jobs easier
* Empty jobs will now be created when the state machine enters the `job`
state
* Jobs will still be persisted only when moving to the next step, so
mutiple empty jobs shouldn't be created
* Will need to move job creation logic into a method. currently living
directly in the state chart
=> Move new job creation logic out of component

src/models/basic-info.js, src/pages/form/steps/basic-info/residence-address.js, src/test-data.js
* We will use `disasterCounty` going forward
=> Remove refs to county

src/components/input/index.js, src/pages/eligible.js, src/schemas/identity.js, src/services/registration.js
* Also fix bug where SSN was required
=> Update registration service server addr

src/schemas/applicant-info.js
* Phone number should have been an optional field, only validating when a value is entered
=> Make phone number an optional field

src/utils/json-transform.js, src/utils/json-transform.test.js
Fixes 18F/eligibility-rules-service#219
=> Transform registration schema to rules schema

src/components/review/disaster-expenses.js, src/components/review/household-matters.js, src/schemas/impact.js, src/schemas/snapshot-review/expenses.js, src/schemas/snapshot-review/impact.js
* Renames previous expense validator to impact, as it was named
incorrectly initially
=> Adds disaster expense validator

src/components/review/income.js, src/schemas/currency-value.js, src/schemas/job.js, src/schemas/snapshot-review/expenses.js, src/schemas/snapshot-review/income.js
* Creates reusable currency value schema
=> Adds validators for income

src/components/fsm.js, src/fsm-config.js, src/locales/en/translation.json, src/pages/eligible.js, src/services/eligibility.js, src/utils/json-transform.js
* Submitting an application now stores data with the persistence layer,
and then calls the rules service to determine basic eligibility
=> Adds correct routing/behavior for registration validation

src/components/fsm.js, src/fsm-config.js, src/locales/en/translation.json, src/locales/utils.js, src/models/config.js, src/pages/welcome/index.js, src/routes.js, src/schemas/language.js, src/test-data.js, src/utils/index.js
* Validate that a language is selected
* Remove the default language selection
* Rework the algo to determine which routethe state machine should
direct the browser to
* Make the complete path explicit in the meta: { path } property of a
state — before the path was coupled to the state name
=> Adds welcome page to xstate

src/components/ui/index.js, src/components/worker-review/review.js, src/services/registration.js, src/utils/json-transform.js
=> Adds infomational header to worker review screen

src/components/snapshot-review/index.js, src/components/worker-review/review.js, src/services/registration.js, src/state-charts/worker.js, src/utils/json-transform.js
* Eligibility is checked once the update button is clicked
* SnapshotReview component needs to be made configurable to allow for
different actions to be taken depending on the context
=> Worker review screen functions like client review

src/schemas/identity.js, src/services/registration.js, src/utils/index.js
* Now passing a properly formatted iso date string
=> Fixes search by date in worker app

src/state-charts/worker.js
* Properly toggle state machine `loading` state property when an eligibility check fails
=> Fixes disabled search button in worker app

src/models/basic-info.js, src/pages/form/steps/resources/assets.js
* Explicitly added basicInfo object to values being passed to the state machine in /assets/index
This property should most likely be an auto include (along with all the other form state)
=> Fix bug where moneyOnHand was not persisted

src/components/dropdown/index.js, src/components/review/household.js, src/locales/en/translation.json, src/pages/form/steps/household/how-many.js, src/pages/form/steps/household/member-names.js
=> Improves household members UI + Copy

src/components/currency-input/index.js, src/components/formik-field/index.js, src/components/wizard/index.js, src/pages/form/steps/resources/jobs.js, src/schemas/job.js
* Also improves existing currency field UI by clearing false positive error message as soon as the field is blurred. Previously, the message wasn't cleared until the next blur event on the form.
=> Use currency field on jobs page

src/components/fsm.js, src/components/header/index.js, src/fsm-config.js, src/locales/en/translation.json, src/pages/eligible.js, src/test-data.js
* Separate the `intialState` loading function from the actual initial state object
* Remove link to home page from header
=> Fix issues with session state caching

src/components/formik-field/index.js, src/components/input/index.js
* Fixes masked input errors with nested formiks
* Fixes autocomplete is chrome
=> Input field fixes

src/components/collapsible/index.js, src/components/review-subsection/index.js, src/components/review/ebt.js, src/state-charts/worker.js
* Close eligibility accordion on approve/deny
* Properly clear state machine context when transitioning to the search page
* Remove unecessary logging
=> Fix ebt validation, other fixes
